# Generated by Django 4.2.4 on 2024-08-30 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_fooditem_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='food_subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='shop.subcategory'),
        ),
    ]
