# Generated by Django 4.2.4 on 2024-09-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('dine_in', 'Dine-In'), ('takeaway', 'Takeaway'), ('delivery', 'Delivery')], default='dine-in', max_length=10),
        ),
    ]
