# Generated by Django 4.2.4 on 2024-08-31 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_outlet_slug_table_slug_delete_outletuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlet',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
