# Generated by Django 4.2.4 on 2024-08-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_fooditem_food_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
