# Generated by Django 4.2.4 on 2024-08-31 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_outlet_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
