# Generated by Django 4.2.4 on 2024-09-08 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_table_area_alter_table_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outlet',
            name='average_preparation_time',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='outlet',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outlet',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='outlet',
            name='minimum_order_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='outlet',
            name='service',
            field=models.CharField(choices=[('dine_in', 'Dine-In'), ('takeaway', 'Takeaway'), ('delivery', 'Delivery')], default='dine_in', max_length=10),
        ),
        migrations.AddField(
            model_name='outlet',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='OperatingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=9)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_hours', to='shop.outlet')),
            ],
            options={
                'unique_together': {('outlet', 'day_of_week')},
            },
        ),
    ]
