# Generated by Django 4.2.4 on 2024-08-31 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_table_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
