# Generated by Django 4.2.4 on 2024-09-22 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_fooditem_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='type',
            field=models.CharField(default='veg', max_length=100),
        ),
    ]
