# Generated by Django 4.2.4 on 2024-09-27 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_outlet_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
    ]
