# Generated by Django 4.2.4 on 2024-09-08 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_outlet_address_outlet_average_preparation_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutletImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='outlet_images/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.outlet')),
            ],
            options={
                'ordering': ['order', 'uploaded_at'],
            },
        ),
    ]
