# Generated by Django 4.2.4 on 2024-08-31 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_variantcategory_itemvariant_variant_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='variants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='shop.variantcategory'),
        ),
    ]
