# Generated by Django 4.2.4 on 2024-09-08 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_outletimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='outlet_logos/'),
        ),
    ]
