# Generated by Django 4.2.4 on 2024-09-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_addon_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='payment_methods',
            field=models.CharField(default='online', max_length=100),
        ),
    ]
