# Generated by Django 4.2.4 on 2024-08-31 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_fooditem_variants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooditem',
            old_name='variants',
            new_name='variant',
        ),
    ]
