# Generated by Django 4.2.4 on 2024-09-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_outlet_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outlet',
            name='service',
        ),
        migrations.AddField(
            model_name='outlet',
            name='services',
            field=models.CharField(default='dine_in', max_length=100),
        ),
    ]
