# Generated by Django 4.2.4 on 2024-09-13 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_outlet_service_outlet_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='shop.menu'),
        ),
    ]
