# Generated by Django 4.2.4 on 2024-09-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_variant_description_addon_item_variant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='variant',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='variant',
            field=models.ManyToManyField(blank=True, null=True, related_name='food_items', to='shop.variantcategory'),
        ),
    ]
