# Generated by Django 4.2.4 on 2024-09-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_outlet_outlet_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
