# Generated by Django 4.2.4 on 2024-09-13 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_addon_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addon',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='shop.menu'),
        ),
    ]
