# Generated by Django 4.2.4 on 2024-09-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_fooditem_variant_fooditem_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemvariant',
            name='variant',
        ),
        migrations.AddField(
            model_name='itemvariant',
            name='variant',
            field=models.ManyToManyField(related_name='item_variants', to='shop.variant'),
        ),
    ]
