# Generated by Django 4.2.4 on 2024-09-13 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_addoncategory_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addoncategory',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addon_categories', to='shop.menu'),
        ),
    ]
