# Generated by Django 4.2.4 on 2024-09-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_order_cooking_instructions_order_order_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='table',
            name='table_number',
        ),
        migrations.AddField(
            model_name='table',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
