# Generated by Django 4.2.4 on 2024-10-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_cartitem_variant_alter_orderitem_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('online', 'Online'), ('cash', 'Cash'), ('card', 'Card'), ('wallet', 'Wallet'), ('upi', 'UPI')], default='online', max_length=100),
        ),
    ]
