# Generated by Django 4.2.4 on 2024-10-04 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('active', 'Active'), ('success', 'Success'), ('pending', 'Pending'), ('expired', 'Expired'), ('terminated', 'Terminated'), ('termination_requested', 'Termination Requested')], default='active', max_length=30),
        ),
    ]
