# Generated by Django 4.2.4 on 2024-10-10 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_ordertimelineitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='prep_start_time',
        ),
    ]
