# Generated by Django 4.2.4 on 2024-10-18 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_remove_order_prep_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('interaction_count', models.PositiveIntegerField(default=0)),
                ('relation_type', models.CharField(choices=[('frequently_bought_together', 'Frequently Bought Together'), ('similar_items', 'Similar Items'), ('complementary_items', 'Complementary Items'), ('substitute_items', 'Substitute Items'), ('popular_items', 'Popular Items')], default='frequently_bought_together', max_length=50)),
                ('last_computed', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('item1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_item1', to='shop.fooditem')),
                ('item2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_item2', to='shop.fooditem')),
            ],
            options={
                'unique_together': {('item1', 'item2')},
            },
        ),
    ]
