# Generated by Django 4.2.4 on 2024-10-20 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_discountcoupon_application_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addon',
            name='item_variant',
            field=models.ManyToManyField(blank=True, related_name='addons', to='shop.itemvariant'),
        ),
    ]
