# Generated by Django 4.2.4 on 2024-10-22 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_alter_addon_item_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='lite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='outlet',
            name='payment_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='OutletDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='outlet_documents/')),
                ('name', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='shop.outlet')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
