# Generated by Django 4.2.4 on 2024-10-23 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_alter_outlet_payment_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='usages', to='shop.discountcoupon'),
        ),
    ]
