# Generated by Django 4.2.4 on 2024-11-17 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_foodcategory_order_fooditem_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fooditem',
            options={'ordering': ['order', 'name']},
        ),
    ]
