# Generated by Django 4.2.4 on 2024-12-07 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_outletdocument_value_payouts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operatinghours',
            options={'verbose_name_plural': 'Operating Hours'},
        ),
        migrations.AlterModelOptions(
            name='payouts',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Payouts'},
        ),
    ]
