# Generated by Django 4.2.4 on 2024-12-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_operatinghours_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcategory',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
