# Generated by Django 4.2.4 on 2024-12-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_foodcategory_active_subcategory_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outlet',
            name='lite',
        ),
        migrations.AddField(
            model_name='outlet',
            name='outlet_type',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('cafe', 'Cafe'), ('bakery', 'Bakery'), ('sweet_shop', 'Sweet Shop'), ('lite', 'Lite')], default='restaurant', max_length=100),
        ),
    ]
