# Generated by Django 4.2.4 on 2024-12-15 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_foodcategory_category_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodcategory',
            old_name='category_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='foodcategory',
            old_name='category_image_url',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='foodcategory',
            old_name='category_slug',
            new_name='slug',
        ),
    ]
